sudo: false

language: python

python:
  - 3.4

install:
  - pip install codecov

script:
  - coverage run run_tests.py

after_success:
  - codecov
  
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: "GdHQrQiVhd86RzikVRjNhIJJsvi91jw3Ylaw0lf2dlNzAf+cGBJreNVJY4LeKxlEa7zp0OQuzBlpZz1JpvTGtTW9cEG1+cPf1F14RHF341tgNdVKjcO9nVKoJnJBC7K0n+OwaRDpsohur1g7HcnqaJQLmGM05cAOEkiUAjlHdKid9z8/hNiSj3arUntG0SrwY8FQjOn3430S/qfQyBhDTY8aW1DATyTic6I9mlbTiJrTE34a/79QAcdJ6efMAD9IaodkY5f4F1BogO1zLVzLDtZgaSDz5m8eTezjWGlx75TOG8k6MClDxuGEg7jneab+Tb8GPPqNxxb2wCRtZiO5sCs9OuntDCyhNZozB/kwwaJDYe8KgZDKy00zkw550hB0WQkYwOE0l9vpTjcTUMmvplak4y33qCE0X+Tf/JE1Wu46sj3nsPwCRPpRaAZfNYJVqxQroG1wcOEroS0V5dHCwuVE9qGDoIoaeBzW3LTk8YJO/fbLLw3LmfivlDMyzD14SYrriW40iOG59QL7xOzV0a/4A3XEvd2xTBctfr1clGiKijrsb/G1fR6ec+l0dLppJFefWL/4n3wnCfJt8kRFcVm5T+BtKiuIG4oN9BpZAzS+rrTWHbIGe+/mx1VlZkWtDx3pNhstb+sGFECv0d5vm/qsw2TXBhMeVfmnP20ZclU="
  password:
    secure: "LVuJ1CXSwVgMMP2I7f4Vf7wK+L7JStLZrtrcWlD0D3lDDug79ulIQhv0GwWmsI29JIv883IMQTZ0BCZRFZlsZu/lYVz4BcP7zeL1E3aKrPfiSxo4856b6U3grtAPZ/mtrxPUmqI/GZX9f48sjqP7FRDe0VrkTdNDMc2wqqHDBZPjSeGhpW62yy5dIHkrftp9Bh+1h74jeJ4RZwNmG470/Gy2Qaf1LLiP1OEazWek19CxNNelUMA1hJnwiVL/1Ef/LTBrP2PNG6NfHg5g0v4n+JaoITfTWHCJLymiiaqvvwn/nz7uWztlfZ5MFwprw3geMLWt7A69yAQjLxUGKmA5PMKzACzka/14WetIeK1mFf5tVb0O6HtO+Divr/gVPPkCV5Xk3wGDCPSrgkdLqiG09cHyrb4SC5TbGPmdbUF06YmnV5oCRBQLHIOmGyv25/mAovMIBnYfthWFwq8lRD25DXhBbfg2ZoRBIrzqYLd8RgqH/C0aNtHCyBoMBW7ICy9dU8LkNf8bqiDWzrAN7UFMw4rQnHBgA85016iJ+YfwI4zkwE0u3qXra8JAkqHnIFeuNNplJn+261NMGszYImfK6rhaP6fs+0vA4O2hZ2ZvPbVnG5AM48UoRR7DUT9Xw3vsYjgpDF7tp/7QIez8Aqwrlt79h0843PdlQw4nBAzH/84="
  on:
    tags: true